sync blog modifications: https://sunway.run/blog/CICDWithTektonAndArgoCD

diff --git a/tekton-task-template/task-update-image-tag.yaml b/tekton-task-template/task-update-image-tag.yaml
--- a/tekton-task-template/task-update-image-tag.yaml
+++ b/tekton-task-template/task-update-image-tag.yaml
@@ -10,36 +10,52 @@ spec:
     - name: commit_id
       description: result of git commit
     - name: project_path
+      type: string
       description: which deployment path to update
+    - name: git_branch
+      description: git branch to checkout (branch, tag, sha, ref…)
+      type: string
+      default: main
+  results:
+    - name: pipeline-end-time
   steps:
     - name: update-image-tag
       image: alpine/git
       script: |
         #!/usr/bin/env sh
-        set -eu
-        if [[ -d $(workspaces.ssh-directory.path) ]]; then
-          mkdir -p ~/.ssh
-          cp $(workspaces.ssh-directory.path)/known_hosts ~/.ssh/known_hosts
-          cp $(workspaces.ssh-directory.path)/id_rsa ~/.ssh/id_rsa
-          chmod 700 ~/.ssh
-          chmod 600 ~/.ssh/*
-        fi
-        
-        # git init only required in network file system pvc, do not required in disk storage pvc, cause nfs deny git search its parent working tree
-        git init
-        git clone git@github.com:sunway910/cicd-demo.git
-        git checkout "$(params.revision)"
-        
-        # cd https://github.com/sunway910/cicd-demo/cicd-demo-helm
-        cd "$(project_path)"
-        # update image tag to the latest one
-        sed -i "s|tag:.*|tag: $(params.commit_id)|" values.yaml || { echo "Failed to update values.yaml"; exit 1; }
-        
-        git config --global user.email "tekton@sunway.run"
-        git config --global user.name "Tekton Bot"
-        
-        git add values.yaml
-        git commit -m "skip ci: update image tag to $(params.commit_id)" || { echo "Failed to commit changes"; exit 1; }
-        git push || { echo "Failed to push changes"; exit 1; }
+        apk add --no-cache bash
+        export TZ=UTC-8
+        exec bash << 'EOF'
+          #!/usr/bin/env bash
+          set -eu
+          if [[ -d $(workspaces.ssh-directory.path) ]]; then
+            mkdir -p ~/.ssh
+            cp $(workspaces.ssh-directory.path)/known_hosts ~/.ssh/known_hosts
+            cp $(workspaces.ssh-directory.path)/id_rsa ~/.ssh/id_rsa
+            chmod 700 ~/.ssh
+            chmod 600 ~/.ssh/*
+          fi
+
+          # git init only required in network file system pvc, do not required in disk storage pvc, cause nfs deny git search its parent working tree
+          # git init
+          # 'git@github.com:sunway910/cicd-demo.git' can be a param
+          git clone git@github.com:sunway910/cicd-demo.git
+          cd cicd-demo
+          git checkout "$(echo $(params.git_branch) | rev | cut -d'/' -f1 | rev)"
+
+          # cd https://github.com/sunway910/cicd-demo/cicd-demo-helm
+          cd "$(project_path)"
+          # update image tag to the latest one
+          sed -i "s|tag:.*|tag: $(params.commit_id)|" values.yaml || { echo "Failed to update values.yaml"; exit 1; }
+
+
+          git config --global user.email "tekton@sunway.run"
+          git config --global user.name "Tekton Bot"
+          git add .
+          echo "Commit changes: skip ci: update image tag to $(params.commit_id)"
+          git commit -m "skip ci: update image tag to $(params.commit_id)" || { echo "Failed to commit changes"; exit 1; }
+          git push || { echo "Failed to push changes"; exit 1; }
+          TZ='Asia/Shanghai' echo -n "$(date '+Date: %Y-%m-%d Time: %H:%M:%S')" > $(results.pipeline-end-time.path)
+        EOF
       securityContext:
         runAsUser: 0
